# Generated by Django 6.0.4 on 2026-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('year_label', models.CharField(max_length=20, null=True)),
                ('fiscal_year', models.IntegerField(null=True)),
                ('equity_capital', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('borrowings', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('debt_to_equity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('year_label', models.CharField(max_length=20, null=True)),
                ('fiscal_year', models.IntegerField(null=True)),
                ('operating_activity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('investing_activity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('financing_activity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_logo', models.TextField(null=True)),
                ('about_company', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('nse_profile', models.TextField(null=True)),
                ('bse_profile', models.TextField(null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('roce_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('roe_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_profitability', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_growth', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_leverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_cashflow', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_dividend', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_coverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('health_label', models.CharField(max_length=20, null=True)),
                ('computed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=50)),
                ('year_label', models.CharField(max_length=20, null=True)),
                ('fiscal_year', models.IntegerField(null=True)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('opm_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_profit_margin_pct', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
    ]
